[package]
name = "prequel-render"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
prequel-encode = { workspace = true }
prequel-session = { workspace = true }
cidre = { workspace = true, features = [
  "av",
  "cv",
  "cm",
  "cat",
  "cg",
  "mtl",
  "blocks",
  "async",
  "dispatch",
  "macos_15_0",
] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
