/**
 * `window.prequel` without a main process behind it.
 *
 * Written out in full and checked with `satisfies DesktopApi` rather than
 * generated by a `Proxy`: a method added to the preload without a twin here
 * fails the gallery's typecheck, where a proxy would answer `undefined` and the
 * component would render something subtly wrong in a screenshot nobody
 * re-reads.
 *
 * Every method answers what a real main would for a Mac in the state the
 * fixtures describe. Anything that would open a dialog, touch the network or
 * change the machine is a no-op that logs, so a shot that trips one shows up
 * in the capture script's console output as `[bridge] <name>`.
 *
 * Subscriptions are kept, and `emit` drives them. That is how an export
 * "progresses" for the export dialog's finished view, and how a device toggle
 * on the dock is seen to change state.
 */
import type { DesktopApi } from "../src/preload/index";
import type {
  AppInfo,
  AuthState,
  BackgroundsCatalogue,
  DockState,
  Entitlement,
  ExportProgress,
  IpcResult,
  PermissionState,
  ProjectSummary,
  TeleprompterPosition,
  TeleprompterState,
  UpdateState,
} from "../src/shared/contract";
import type { ScenePreset } from "../src/shared/scene-presets";
import { sanitiseScenePresets } from "../src/shared/scene-presets";
import type { EditorSession } from "../src/shared/contract";
import * as fixtures from "./fixtures";
import { exportUrl } from "./media-url";
import { loadSession } from "./session";

export interface Fixtures {
  dock: DockState;
  teleprompter: TeleprompterState;
  /** What the island is told when it asks where the reader is. */
  teleprompterPosition: TeleprompterPosition;
  permissions: PermissionState[];
  auth: AuthState;
  licence: Entitlement;
  update: UpdateState;
  appInfo: AppInfo;
  loginItem: boolean | null;
  /** Where the export dialog says the file went. */
  exportPath: string;
}

export const DEFAULT_FIXTURES: Fixtures = {
  dock: fixtures.DOCK,
  teleprompter: fixtures.TELEPROMPTER,
  teleprompterPosition: fixtures.TELEPROMPTER_POSITION,
  permissions: fixtures.permissions(),
  auth: fixtures.AUTH,
  licence: fixtures.TRIAL,
  update: fixtures.UPDATE,
  appInfo: fixtures.APP_INFO,
  loginItem: true,
  exportPath: "/Users/you/Desktop/Prequel demo.mp4",
};

type Listener = (value: never) => void;

export interface Bridge {
  api: DesktopApi;
  /** Pushes a value to everything subscribed on a channel. */
  emit<T>(channel: string, value: T): void;
  fixtures: Fixtures;
}

function ok<T>(value: T): Promise<IpcResult<T>> {
  return Promise.resolve({ ok: true, value });
}

function noop(name: string) {
  return (...args: unknown[]) => {
    console.warn(`[bridge] ${name}`, ...args);
    return Promise.resolve(undefined);
  };
}

async function json<T>(url: string): Promise<T | null> {
  const response = await fetch(url);
  return response.ok ? ((await response.json()) as T) : null;
}

export function createBridge(overrides: Partial<Fixtures> = {}): Bridge {
  const state: Fixtures = { ...DEFAULT_FIXTURES, ...overrides };
  const listeners = new Map<string, Set<Listener>>();

  const subscribe =
    <T>(channel: string) =>
    (listener: (value: T) => void): (() => void) => {
      const set = listeners.get(channel) ?? new Set();
      set.add(listener as Listener);
      listeners.set(channel, set);
      return () => set.delete(listener as Listener);
    };

  const emit = <T>(channel: string, value: T) => {
    for (const listener of listeners.get(channel) ?? []) (listener as (v: T) => void)(value);
  };

  const dock = (patch: Partial<DockState>): Promise<DockState> => {
    state.dock = { ...state.dock, ...patch };
    emit("dock", state.dock);
    return Promise.resolve(state.dock);
  };

  let sessionCache: Promise<EditorSession | null> | null = null;
  let sessionName: string | null = null;

  const api = {
    getAppInfo: () => Promise.resolve(state.appInfo),

    permissions: {
      list: () => Promise.resolve(state.permissions),
      request: (id) => {
        state.permissions = state.permissions.map((p) =>
          p.id === id ? { ...p, granted: true } : p,
        );
        return Promise.resolve(state.permissions);
      },
      ensureDevice: () => Promise.resolve(true),
    },

    welcome: {
      done: noop("welcome.done"),
      relaunch: noop("welcome.relaunch"),
    },

    loginItem: {
      get: () => Promise.resolve(state.loginItem),
      set: (enabled) => {
        state.loginItem = enabled;
        emit("loginItem", enabled);
        return Promise.resolve(enabled);
      },
      onChange: subscribe<boolean>("loginItem"),
    },

    settings: {
      setShortcut: (accelerator) => {
        void dock({ preferences: { ...state.dock.preferences, toggleShortcut: accelerator } });
        return ok(accelerator);
      },
    },

    dock: {
      state: () => Promise.resolve(state.dock),
      chooseMode: async (mode) => ({ ok: true, value: await dock({ activeMode: mode }) }),
      updatePreferences: (patch) => dock({ preferences: { ...state.dock.preferences, ...patch } }),
      record: () => ok(state.dock),
      stop: () => ok(undefined),
      discard: () => ok(undefined),
      togglePause: () => ok(undefined),
      close: noop("dock.close"),
      // A native menu. Nothing picked, which is what a click elsewhere does.
      openMenu: () => Promise.resolve(null),
      // Main resizes the window to this; the gallery's column is `w-max`.
      setWidth: () => Promise.resolve(),
      reportCameraError: (message) => dock({ cameraError: message }),
      onCameraHover: subscribe<boolean>("cameraHover"),
      onChange: subscribe<DockState>("dock"),
    },

    teleprompter: {
      state: () => Promise.resolve(state.teleprompter),
      setScript: (text) => {
        state.teleprompter = { ...state.teleprompter, script: text };
        emit("teleprompter", state.teleprompter);
        return Promise.resolve();
      },
      openScript: noop("teleprompter.openScript"),
      // A click on a word: the reader saying where they are.
      jump: (jump) => {
        if ("to" in jump && typeof jump.to === "number") {
          state.teleprompterPosition = { ...state.teleprompterPosition, position: jump.to };
          emit("teleprompterPosition", state.teleprompterPosition);
        }
        return Promise.resolve();
      },
      togglePause: () => {
        state.teleprompter = { ...state.teleprompter, paused: !state.teleprompter.paused };
        emit("teleprompter", state.teleprompter);
        return Promise.resolve();
      },
      // Answered on the next tick, as main's push would be: the island
      // subscribes and then asks, in that order.
      ready: () => {
        setTimeout(() => emit("teleprompterPosition", state.teleprompterPosition), 0);
      },
      onChange: subscribe<TeleprompterState>("teleprompter"),
      onVisible: subscribe<boolean>("teleprompterVisible"),
      onPosition: subscribe<TeleprompterPosition>("teleprompterPosition"),
    },

    selection: {
      onSetup: subscribe("selectionSetup"),
      setup: () => Promise.resolve(null),
      choose: noop("selection.choose"),
      cancel: noop("selection.cancel"),
      countdown: noop("selection.countdown"),
    },

    editor: {
      session: (name) => {
        if (sessionName !== name || !sessionCache) {
          sessionName = name;
          sessionCache = loadSession(name);
        }
        return sessionCache.then((value) => ({ ok: true as const, value }));
      },
      leave: () => ok(undefined),
      // The edit is not saved anywhere: the fixture recording's `project.json`
      // must come out of a run exactly as it went in.
      saveProject: () => ok(undefined),
      wallpaper: () => ok(null),
      pickImage: () => ok(null),
      pickWatermark: () => ok(null),
      presetImage: () => ok(null),

      export: {
        choose: () => ok(state.exportPath),
        /**
         * A pretend render: three ticks and done, over about half a second.
         * The dialog's finished view is what the docs want, and it plays back
         * `exportUrl(name)`, which the server answers with the screen track.
         */
        start: () => {
          const total = 600;
          const path = state.exportPath;
          const step = (framesDone: number, stage: ExportProgress["stage"]) =>
            emit<ExportProgress>("exportProgress", {
              stage,
              framesDone,
              framesTotal: total,
              outputPath: stage === "done" ? path : null,
              error: null,
            });
          setTimeout(() => step(0, "preparing"), 50);
          setTimeout(() => step(200, "rendering"), 200);
          setTimeout(() => step(450, "rendering"), 350);
          setTimeout(() => step(total, "finalising"), 500);
          setTimeout(() => step(total, "done"), 650);
          return ok(undefined);
        },
        cancel: () => ok(undefined),
        onProgress: subscribe<ExportProgress>("exportProgress"),
        copy: () => ok(undefined),
        drag: () => {},
      },

      share: {
        start: () => ok(undefined),
        cancel: () => ok(undefined),
        onProgress: subscribe("shareProgress"),
      },

      transcribe: {
        start: () => ok(undefined),
        cancel: () => ok(undefined),
        onProgress: subscribe("transcribeProgress"),
      },

      backgrounds: {
        catalogue: async () => ({
          ok: true as const,
          value: await json<BackgroundsCatalogue>("/fixture/backgrounds.json"),
        }),
        // The thumbnails are the cache on this Mac; whichever are there, are.
        thumbnail: () => ok(true),
        ensure: async (_dir, file) => {
          const response = await fetch(
            `/media/recording/${encodeURIComponent(sessionName ?? "")}/${encodeURIComponent(file)}`,
            { method: "HEAD" },
          );
          return { ok: true as const, value: response.ok };
        },
      },

      scenePresets: {
        list: async () => ({
          ok: true as const,
          value: sanitiseScenePresets(await json("/fixture/scene-presets.json")),
        }),
        save: (preset) => ok([preset] as ScenePreset[]),
        rename: () => ok([] as ScenePreset[]),
        remove: () => ok([] as ScenePreset[]),
        applyImage: () => ok(null),
        applyWatermark: () => ok(false),
      },

      bitmaps: {
        /**
         * Into the overlay directory, never the recording. The URL the
         * renderer then asks for is the same one main would serve, and the
         * media middleware reads the overlay first. Captions and texts alike:
         * the file name carries its own folder.
         */
        write: async (_kind, _dir, file, bytes) => {
          const name = encodeURIComponent(sessionName ?? "");
          await fetch(`/overlay/${name}/${encodeURIComponent(file)}`, {
            method: "PUT",
            body: bytes as BodyInit,
          });
          return { ok: true as const, value: file };
        },
        sweep: () => ok(undefined),
      },

      // No hosted faces in the gallery: the shots are set in the macOS list,
      // which needs nothing fetched.
      fonts: {
        catalogue: () => ok(null),
        ensure: () => ok(false),
      },
    },

    sources: {
      list: () => ok([fixtures.DISPLAY, fixtures.SAFARI]),
    },

    library: {
      reveal: noop("library.reveal"),
    },

    projects: {
      list: async (limit = 24, offset = 0) => {
        const all = (await json<ProjectSummary[]>("/fixture/recordings.json")) ?? [];
        return {
          ok: true as const,
          value: { projects: all.slice(offset, offset + limit), total: all.length },
        };
      },
      rename: () => ok(undefined),
      delete: () => ok(false),
      savePoster: () => ok(undefined),
      saveFilmstrip: () => ok(undefined),
    },

    workspace: {
      onNavigate: subscribe<string>("navigate"),
      onSection: subscribe("section"),
      ready: () => Promise.resolve(),
    },

    licence: {
      state: () => Promise.resolve(state.licence),
      check: () => Promise.resolve(state.licence),
      upgrade: noop("licence.upgrade"),
      prompted: () => {},
      onChange: subscribe<Entitlement>("licence"),
    },

    auth: {
      state: () => Promise.resolve(state.auth),
      signIn: () => ok(undefined),
      signOut: () => ok(undefined),
      openDashboard: () => ok(undefined),
      onChange: subscribe<AuthState>("auth"),
    },

    update: {
      state: () => Promise.resolve(state.update),
      check: () => Promise.resolve(state.update),
      download: () => Promise.resolve(state.update),
      install: noop("update.install"),
      open: noop("update.open"),
      onChange: subscribe<UpdateState>("update"),
    },
  } satisfies DesktopApi;

  return { api, emit, fixtures: state };
}

/** So a shot can point the finished export dialog at something that plays. */
export { exportUrl };
